apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uptimekumainstances.kuma.anshuman.github.io
spec:
  group: kuma.anshuman.github.io
  names:
    kind: UptimeKumaInstance
    listKind: UptimeKumaInstanceList
    plural: uptimekumainstances
    singular: uptimekumainstance
    shortNames:
      - uki
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                url:
                  type: string
                  description: URL of the Uptime Kuma instance
                username:
                  type: string
                  description: Username for authentication
                passwordSecretRef:
                  type: string
                  description: Password secret reference
              required:
                - url
            status:
              type: object
              properties:
                connected:
                  type: boolean
                  description: Connected indicates if the controller can reach the instance
                message:
                  type: string
                  description: Message provides additional status information
      subresources:
        status: {}